# Generated by Django 5.0.6 on 2024-05-11 00:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalago', '0002_cat_municipios_fk_cat_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('profesion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pk_persona_curp', models.CharField(max_length=18, verbose_name='Curp')),
                ('apellido_paterno', models.CharField(max_length=30, null=True, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=30, null=True, verbose_name='Apellido Materno')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Nacimiento')),
                ('personascol', models.CharField(max_length=45, null=True)),
                ('fk_enum_sexo', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=6, null=True, verbose_name='Sexo')),
                ('fk_enum_tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo de sangre')),
                ('fk_enum_estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)')], max_length=10, null=True, verbose_name='Estado civil')),
                ('telefono', models.CharField(max_length=10, null=True, verbose_name='Telefomo')),
                ('fk_codigo_postal', models.CharField(max_length=6, null=True, verbose_name='Codigo postal')),
                ('calle', models.CharField(max_length=45, null=True, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=10, null=True, verbose_name='Numero exterior')),
                ('numero_interior', models.CharField(max_length=10, null=True, verbose_name='Numero Interior')),
                ('habla_lengua_indigena', models.BooleanField(null=True, verbose_name='Lengua indigena')),
                ('cual_lengua_indigena', models.CharField(max_length=45)),
                ('fk_cat_asentamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalago.cat_tipo_asentamientos', verbose_name='Asentamiento')),
                ('fk_cat_escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalago.cat_escolaridades', verbose_name='Escolaridad')),
                ('fk_municipio_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_nacimiento_personas', to='Catalago.cat_municipios', verbose_name='Municipio')),
                ('fk_pais_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_nacimiento_personas', to='Catalago.cat_pais', verbose_name='Paiz Nacimineto')),
                ('fk_pais_vive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_vive_personas', to='Catalago.cat_pais', verbose_name='Pais Actual')),
                ('fk_religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Catalago.cat_religiones', verbose_name='Religion')),
                ('otro_municipio_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otro_municipio_nacimiento_personas', to='Catalago.cat_municipios', verbose_name='Segundo Municipio')),
            ],
            options={
                'unique_together': {('pk_persona_curp',)},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(blank='', default='', upload_to='foto/')),
                ('ocupacion_anterior', django_ckeditor_5.fields.CKEditor5Field()),
                ('ocupacion_actual', django_ckeditor_5.fields.CKEditor5Field()),
                ('fk_persona_curp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.persona')),
            ],
            options={
                'unique_together': {('fk_persona_curp',)},
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pk_trabajador_curp', models.CharField(max_length=18, verbose_name='Curp')),
                ('apellido_paterno', models.CharField(default='', max_length=30, null=True, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(default='', max_length=30, null=True, verbose_name='Apellido Materno')),
                ('nombre', models.CharField(max_length=40, null=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(null=True)),
                ('fk_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.doctor', verbose_name='Doctor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('pk_trabajador_curp',)},
            },
        ),
    ]
