# Generated by Django 5.0.6 on 2024-05-12 02:39

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_alter_paciente_foto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='persona',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='Registro.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion_actual',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ocupacion Actual'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion_anterior',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ocupacion Anterior'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fk_persona_curp',
        ),
    ]
