# Generated by Django 5.0.6 on 2024-05-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_alter_paciente_unique_together_persona_paciente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fk_persona_curp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.persona', verbose_name='Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('fk_persona_curp',)},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='paciente',
        ),
    ]
