# Generated by Django 5.0.6 on 2024-05-12 21:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_alter_trabajador_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trabajador',
            unique_together={('usuario',)},
        ),
    ]
